#配置文件示例：
#1ll73hur1bhm:                          # CDKey内容
#  command: 'eco give {player} 100 '    # 使用CDK后要执行的指令
#  op: true                             # 是否以OP（控制台）身份执行指令
#插件作者：小安 QQ：286526681 有任何问题或者任何建议欢迎随时联系我哟~